name: Fencinglog
options:
  bundleIdPrefix: com.shimondeitel.fencinglog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Fencinglog:
    type: application
    platform: iOS
    sources:
      - path: Fencinglog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fencinglog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Fencinglog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  FencinglogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FencinglogTests
      - path: Fencinglog.storekit
    dependencies:
      - target: Fencinglog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fencinglog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  FencinglogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FencinglogUITests
    dependencies:
      - target: Fencinglog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fencinglog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Fencinglog:
    build:
      targets:
        Fencinglog: all
        FencinglogTests: [test]
        FencinglogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Fencinglog.storekit
    test:
      config: Debug
      storeKitConfiguration: Fencinglog.storekit
      targets:
        - FencinglogTests
        - FencinglogUITests
    archive:
      config: Release
